import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Computer science and engineering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello World!</h1>
      
        <p className={styles.description}>
           {' I\'m Osvaldo Abel, I\'m a Software Engineer'}
          <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Projects &rarr;</h2>
            <p>Here you will see some side projects i'm involved with or i created from scratch. </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Posts &rarr;</h2>
            <p>Here you can see all my blog posts, sorted from newest to the oldest!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Books &rarr;</h2>
            <p>Some books i read & i recommend to every programmer</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/osvaldoabel"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built with <span> &nbsp; &#10084;</span>&nbsp;  by Osvaldo Abel{' '}
        </a>
      </footer>
    </div>
  )
}
